name: Python Quality Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality_checks:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint ruff black bandit pytype
          
      - name: Pylint
        run: |
          pylint $(git ls-files '*.py')
        continue-on-error: true
        
      - name: Ruff
        run: |
          ruff check $(git ls-files '*.py')
        continue-on-error: true
        
      - name: Black
        run: |
          black --check $(git ls-files '*.py')
        continue-on-error: true
        
      - name: Bandit
        run: |
          bandit -r $(git ls-files '*.py')
        continue-on-error: true
        
      - name: Pytype
        run: |
          pytype $(git ls-files '*.py')
        continue-on-error: true